### ISSUE TITLE
Tech Doc : Image Element Error - Object Reference not set to instance

### ISSUE THREAD

**Issue by srikumarradha1969** [ArasLabs/content-generator-samples#1]
Hi!

I am getting the following error when I attempt to insert an image to a Tech Doc Element : "Object Reference not set to instance of an object". 

Will be grateful if someone can tell me what's not right in the code.

//MethodTemplateName=CSharp:Aras.TDF.ContentGenerator(Strict);
ItemDocumentElement targetItem = targetElement as ItemDocumentElement;
if (targetItem != null) {
targetItem.ClearChilds();
ImageDocumentElement imageElement = (ImageDocumentElement) this.Factory.NewElement("graphic");

// get tp_Image item from Innovator
Item imageItem = this.Factory.InnovatorInstance.newItem("tp_Image", "get");
//Item imageItem = this.Factory.InnovatorInstance.getItemById("tp_image", "878E7491168C4DD39348D2DF6E5841CB");
imageItem.setID("878E7491168C4DD39348D2DF6E5841CB");
imageItem = imageItem.apply();

// set reference on image item
imageElement.SetImage(imageItem);

targetItem.AddChild(imageElement);

}

**Comment by EliJDonahue** [comment]
Hi srikumarradha1969,

I believe the issue may be the following lines:

```
ItemDocumentElement targetItem = targetElement as ItemDocumentElement;
if (targetItem != null) {
    targetItem.ClearChilds();

    // ok code

    targetItem.AddChild(imageElement);
}
```

Try removing the targetElement/targetItem code and see if that fixes the issue.

```
//MethodTemplateName=CSharp:Aras.TDF.ContentGenerator(Strict);
ImageDocumentElement imageElement = (ImageDocumentElement) this.Factory.NewElement("graphic");

// get tp_Image item from Innovator
Item imageItem = this.Factory.InnovatorInstance.newItem("tp_Image", "get");
imageItem.setID("878E7491168C4DD39348D2DF6E5841CB");
imageItem = imageItem.apply();

// set reference on image item
imageElement.SetImage(imageItem);
```

**Comment by srikumarradha1969** [comment]
Hi Eli

The issue is not fixing after removing the targetitem/element code and I am getting the same error. It was inserted earlier since from the reference we have of the "ItemInfo" Content Generator, it begins with a ItemDocumentElement, to which a TableDocumentElement is added as a child. So I thought that probably, the ImageDocumentElement would also have to be dealt with similarly, so the "TargetItem".  Maybe the APIs would help.
With warm regards
Srikumar

**Comment by EliJDonahue** [comment]
Hi Srikumar,

I don't have any public APIs I can share for content generators (Yet, I'm working on this!). For now, the best I can do is share the samples in this repo. Can you share your schema and content generator method? I will see if I can reproduce the error and figure out the cause. What version of Innovator are you using?

**Comment by srikumarradha1969** [comment]
Hi Eli
Sorry..the delay in my reply because I was out of station for few days. I am attaching the following: -
(a) The content generator method labs_ItemInfoBlockImageCreation, the c# Server method in my Aras 11 sp12 installation
(b) The schema - unchanged from "Standard" which includes ItemInfo, except for change of the content generator file to the one attached and described below.

The basic aim of the content generator is simply to extend the existing Aras Labs ItemInfo to also show thumbnail images of the Part being imported into the Tech Doc. As of now, new tp_Images and corresponding tp_Blocks are generated successfully for each Part BOM (Item Number and Name set to match that of the Part BOM Item). However, I am unable to attach the tp_Image to corresponding tp_Block through this content generator, outside the current target document. The plan is to then import the tp_Block (with image) into the target document. The highlighted portion is where I am getting the error mentioned earlier by me that object reference is not found. Unlike the cases where a Table or Text Element can be added as child to target document element, I am unable to add the child Image Element due to above error.

I also tried another route which is to through server code add a tp_ImageReference to the matching tp_Block and add the tp_Image as child. However, here, I am not sure as to how to set the reference_id property of the tp_ImageReference relationship item. This portion of code is commented in my attached file.
[labs_ItemInfoBlockImageCreation.pdf](https://github.com/ArasLabs/content-generator-samples/files/2679649/labs_ItemInfoBlockImageCreation.pdf)
![content_gen_4](https://user-images.githubusercontent.com/43463668/49997885-c93bb980-ffb8-11e8-93d0-7812bf457049.png)

Hope you may be able to now look into this at your end and help out. Thanks for all the support !
Regards
Srikumar

**Comment by srikumarradha1969** [comment]
Hi Eli

Glad to mention that I have now been able to find out the reason for the error...the schema for "Graphic" was not matching with new tp_Image creation in the content generator which is "graphic" ! So I am now able to use by content generator for the desired tasks mentioned above.
Thanks for all your support.
With warm regards
Srikumar
